# Generated by Django 4.0.4 on 2022-06-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/149/149071.png', max_length=9999),
        ),
    ]
