# Generated by Django 4.0.4 on 2022-05-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventDriven', '0002_category_remove_event_category_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categoryy',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='EventDriven.category'),
            preserve_default=False,
        ),
    ]
