# Generated by Django 4.0.4 on 2022-05-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventDriven', '0006_remove_event_date_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='event_name',
        ),
    ]
