# Generated by Django 4.0.4 on 2022-05-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventDriven', '0007_cart_limited_integer_field_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='limited_integer_field',
            new_name='total_tickets',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
