# Generated by Django 4.0.4 on 2022-05-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventDriven', '0007_remove_cart_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
