# Generated by Django 4.0.4 on 2022-05-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventDriven', '0008_rename_limited_integer_field_cart_total_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
