# Generated by Django 4.0.4 on 2022-06-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventDriven', '0012_delivery_remove_booking_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
    ]
