# Generated by Django 4.0.4 on 2022-06-02 20:08

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('EventDriven', '0013_remove_booking_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip',
            new_name='house_no',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='cvc',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='expiration_month',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='expiration_year',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(2200)]),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
