# Generated by Django 4.0.4 on 2022-06-02 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventDriven', '0014_rename_zip_address_house_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='cvc',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='expiration_year',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(2222), django.core.validators.MinValueValidator(2022)]),
        ),
    ]
