# Generated by Django 4.0.4 on 2022-06-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventDriven', '0016_remove_cart_event_id_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=255),
        ),
    ]
